/**
 * Quarkus CIS Home service
 * Quarkus ChristInformationSystem
 *
 * The version of the OpenAPI document: 1.0
 * Contact: dominik@christ-rlp.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MeetingSessionBookingRoot } from './meetingSessionBookingRoot';
import { SessionTimeStamp } from './sessionTimeStamp';
import { MeetingSessionTimeBookingTime } from './meetingSessionTimeBookingTime';
import { MeetingSessionId } from './meetingSessionId';


export interface MeetingSessionTimeBooking { 
    root?: MeetingSessionBookingRoot;
    session?: MeetingSessionId;
    time?: MeetingSessionTimeBookingTime;
    times?: Array<SessionTimeStamp>;
}

