export * from './wdysCollaboration.service';
import { WdysCollaborationService } from './wdysCollaboration.service';
export * from './wdysDashboard.service';
import { WdysDashboardService } from './wdysDashboard.service';
export * from './wdysMeeting.service';
import { WdysMeetingService } from './wdysMeeting.service';
export * from './wdysMeetingsessionQuery.service';
import { WdysMeetingsessionQueryService } from './wdysMeetingsessionQuery.service';
export * from './wdysNotes.service';
import { WdysNotesService } from './wdysNotes.service';
export * from './wdysParticipant.service';
import { WdysParticipantService } from './wdysParticipant.service';
export * from './wdysSession.service';
import { WdysSessionService } from './wdysSession.service';
export * from './wdysTimebooking.service';
import { WdysTimebookingService } from './wdysTimebooking.service';
export * from './wdysTodo.service';
import { WdysTodoService } from './wdysTodo.service';
export const APIS = [WdysCollaborationService, WdysDashboardService, WdysMeetingService, WdysMeetingsessionQueryService, WdysNotesService, WdysParticipantService, WdysSessionService, WdysTimebookingService, WdysTodoService];
